extends Node

enum TYPES_OF_ANTS { NO_UNIT = 0, ANT_MIN = 1,ANT_DEFAULT, ANT_MAX}
enum TYPES_OF_STATS { STATS_MIN = 1,LIFE, ATTACK, DEFENSE, HAPPINESS, ACTION_POINTS, NUMBER_OF_MOVEMENT }
enum TYPES_OF_HELMETS { UNIT_EXPERIENCE_MIN = 1,BRONZE, SILVER, GOLD }

const HELMETS_DEFENSE: PoolIntArray = PoolIntArray([2, 4, 6])


func _ready() -> void:
	#assert(HELMETS_DEFENSE.size() == TYPES_OF_HELMETS.size())
	pass
